### ISSUE TITLE
EML R-package

### ISSUE THREAD

**Issue by ErlendNilsen** [LivingNorway/LivNoR#2]
To prepare the EML metadata document, we will probably make use of the EML-package for R (https://cran.r-project.org/web/packages/EML/index.html). We should explore that package at an early phase of this project.

**Comment by DrMattG** [comment]
Also we might learn some best practice from https://github.com/DataONEorg/rdataone

**Comment by DrMattG** [comment]
Have you seen this package? 
Views eml in shiny 
`                                           
library("emldown")

render_eml(system.file("extdata", "hampton_underice.xml", package = "emldown"))
`

**Comment by DrMattG** [comment]
I have included these packages in the workplan. We need to evaluate these packages and/or functions to assess if they are 1) well maintained and hence good dependencies and 2) are suitable to our needs. If not we can better recreate the functionality within our package(s) rather than risk dependency issues further down the line. I'll close this comment now.
